### ISSUE TITLE
drgn doesn't handle XZ compressed kernel modules

### ISSUE THREAD

**Issue by danobi** [osandov/drgn#11]
Built and installed from source on fedora 30:

```
$ cd /usr/lib/modules/5.1.18-300.fc30.x86_64/kernel 
$ ls
arch  crypto  drivers  fs  kernel  lib  mm  net  security  sound  virt
$ rpm -qf arch
kernel-core-5.1.18-300.fc30.x86_64
$ sudo drgn
could not get debugging information for:
kernel (could not find vmlinux)
/usr/lib/modules/5.1.18-300.fc30.x86_64/kernel/drivers/net/usb/ipheth.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.1.18-300.fc30.x86_64/kernel/crypto/ccm.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.1.18-300.fc30.x86_64/kernel/drivers/input/misc/uinput.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.1.18-300.fc30.x86_64/kernel/fs/fuse/fuse.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
... 167 more
drgn 0.0.1 (using Python 3.7.4)
For help, type help(drgn).
>>> import drgn
>>> from drgn import cast, container_of, execscript, NULL, Object, reinterpret
>>> from drgn.helpers.linux import *
>>>
>>> find_task(prog, 1).cred.user.locked_vm
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.1-py3.7-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 117, in find_task
    return pid_task(find_pid(prog_or_ns, pid), prog['PIDTYPE_PID'])
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.1-py3.7-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 35, in find_pid
    ns = prog_or_ns['init_pid_ns'].address_of_()
KeyError: 'init_pid_ns'
```

**Comment by danobi** [comment]
Ah ok. I'll give it a try when I'm on a stronger internet connection. Feel free to rename/close the issue.

**Comment by danobi** [comment]
Looks like drgn is having trouble locating the debug files. Not sure if you use debuglink but it seems like fedora has put the debuginfos in a non-standard location.
```
$ pwd
/usr/lib/modules/5.2.11-200.fc30.x86_64/kernel/kernel/trace

$ readelf -p .gnu_debuglink ring_buffer_benchmark.ko

String dump of section '.gnu_debuglink':
  [     0]  ring_buffer_benchmark.ko.debug
  [    23]  j

$  ll /usr/lib/debug/lib/modules/5.2.14-200.fc30.x86_64/kernel/kernel/trace/ring_buffer_benchmark.ko.debug
-r--r--r--. 1 root root 229K Sep 10 05:34 /usr/lib/debug/lib/modules/5.2.14-200.fc30.x86_64/kernel/kernel/trace/ring_buffer_benchmark.ko.debug
```

**Comment by danobi** [comment]
```
$ uname -r
5.2.11-200.fc30.x86_64
$ sudo drgn
[sudo] password for dlxu:
could not get debugging information for:
kernel (could not find vmlinux)
/usr/lib/modules/5.2.11-200.fc30.x86_64/kernel/drivers/char/lp.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.2.11-200.fc30.x86_64/kernel/drivers/parport/parport.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.2.11-200.fc30.x86_64/kernel/drivers/net/usb/ipheth.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
/usr/lib/modules/5.2.11-200.fc30.x86_64/kernel/drivers/thunderbolt/thunderbolt.ko.xz (could not get section addresses: libelf error: invalid `Elf' handle)
... 162 more
drgn 0.0.1 (using Python 3.7.4)
For help, type help(drgn).
>>> import drgn
>>> from drgn import cast, container_of, execscript, NULL, Object, reinterpret
>>> from drgn.helpers.linux import *
>>> find_task(prog, 1).cred.user.locked_vm.counter
Traceback (most recent call last):
  File "/usr/lib64/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.1-py3.7-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 117, in find_task
    return pid_task(find_pid(prog_or_ns, pid), prog['PIDTYPE_PID'])
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.1-py3.7-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 35, in find_pid
    ns = prog_or_ns['init_pid_ns'].address_of_()
KeyError: 'init_pid_ns'
```

**Comment by osandov** [comment]
Ah okay you're running 5.2.11-200.fc30.x86_64, but the dnf command installed the debugging information for the latest kernel, 5.2.14-200.fc30.x86_64. You can either reboot into that kernel or try:

```
sudo dnf install --enablerepo=updates-debuginfo kernel-debuginfo-$(uname -r)
```

**Comment by danobi** [comment]
Ran
```
sudo dnf install --enablerepo=updates-debuginfo kernel-debuginfo-$(uname -r)
```
again and it works now. I think my kernel version and debuginfo were just constantly skewed.

**Comment by jfernandez** [comment]
@osandov did you add support for compressed modules?

**Comment by osandov** [comment]
@jfernandez gz and xz compressed modules should work as long as drgn was compiled with elfutils version >= 0.175. I just realized that zstd compressed modules need a code change in drgn, so let me know if that affects you.

**Comment by jfernandez** [comment]
@osandov I realized that my config was using zstd compression. I'm using Arch Linux drgn package. I disabled compression to get around this.

**Comment by osandov** [comment]
FYI, `.gz`, `.xz`, and `.zst` modules are all supported as of 4e83130008e9c28c3d775a0ab40075f2f9123720 (assuming drgn was built against a new enough elfutils).
