### ISSUE TITLE
KeyError: 'PIDTYPE_PID' error

### ISSUE THREAD

**Issue by milisarge** [osandov/drgn#161]
i am trying to ps.py from examples and getting below error
```
# drgn
drgn 0.0.18 (using Python 3.9.2, elfutils 0.186, with libkdumpfile)
could not get debugging information for:
/usr/src/linux-5.14.16-milis/vmlinux (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/net/wireless/cfg80211.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/sound/core/seq/snd-seq-dummy.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/sound/core/snd-hrtimer.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/net/8021q/8021q.ko.xz (libdwfl error: No DWARF information found)
... 78 more
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, offsetof, reinterpret, sizeof
>>> from drgn.helpers.linux import *
>>> for task in for_each_task(prog):
...     pid = task.pid.value_()
...     comm = task.comm.string_().decode()
...     print(f"{pid:<10} {comm}")
... 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/drgn/helpers/linux/pid.py", line 71, in for_each_task
    PIDTYPE_PID = prog["PIDTYPE_PID"].value_()
KeyError: 'PIDTYPE_PID'
```

**Comment by osandov** [comment]
It looks like your kernel build does not have debugging information, which drgn needs:

```
could not get debugging information for:
/usr/src/linux-5.14.16-milis/vmlinux (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/net/wireless/cfg80211.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/sound/core/seq/snd-seq-dummy.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/sound/core/snd-hrtimer.ko.xz (libdwfl error: No DWARF information found)
/usr/lib/modules/5.14.16-milis/kernel/net/8021q/8021q.ko.xz (libdwfl error: No DWARF information found)
... 78 more
```
