### ISSUE TITLE
Add Architecture Support to main part of the manual

### ISSUE THREAD

**Issue by marxin** [osandov/drgn#288]
It's currently available here:
https://drgn.readthedocs.io/en/latest/release_highlights/0.0.22.html#s390x-support

but it would be better to have it somewhere in the main part of the manual.

**Comment by marxin** [comment]
I've just tried creating a Aarch64 vmcore and if I open it I get:

```
marxin@marxinbox:~/Programming/testcases/crash/aarch64> drgn --core vmcore
drgn 0.0.22+136.g26834be (using Python 3.10.9, elfutils 0.188, with libkdumpfile)
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, offsetof, reinterpret, sizeof
>>> from drgn.helpers.common import *
>>> from drgn.helpers.linux import *
warning: could not get debugging information for:
/lib/modules/6.2.0-1-default/kernel/crypto/algif_hash.ko.zst (could not get section addresses: could not read memory from kdump: Excluded page: 0xffff08c983a0a828)
/lib/modules/6.2.0-1-default/kernel/crypto/af_alg.ko.zst (could not get section addresses: could not read memory from kdump: Excluded page: 0xffff08c984d23280)
/lib/modules/6.2.0-1-default/kernel/net/packet/af_packet.ko.zst (could not get section addresses: could not read memory from kdump: Excluded page: 0xffff08ca86a5c900)
/lib/modules/6.2.0-1-default/kernel/net/ipv4/netfilter/nft_fib_ipv4.ko.zst (could not get section addresses: could not read memory from kdump: Excluded page: 0xffff08caaa109828)
/lib/modules/6.2.0-1-default/kernel/net/netfilter/nft_fib.ko.zst (could not get section addresses: could not read memory from kdump: Excluded page: 0xffff08caaa092780)
... 84 more
>>> drgn.Architecture
<enum 'Architecture'>
>>> prog.platform
Platform(<Architecture.AARCH64: 3>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)
>>> next(for_each_task(prog))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/marxin/.local/lib/python3.10/site-packages/drgn/cli.py", line 75, in _displayhook
    text = value.format_(columns=shutil.get_terminal_size((0, 0)).columns)
NotImplementedError: integer values larger than 64 bits are not yet supported
```

So it's likely not working unless I made a stupid mistake somewhere.
