### ISSUE TITLE
OverflowError thrown by prog.symbol()

### ISSUE THREAD

**Issue by sdimitro** [osandov/drgn#30]
We were hitting an issue with sdb that looked like this:
```
sdb> stacks
TASK_STRUCT        STATE             COUNT
==========================================
0xffffffff862423c0
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
        ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
        Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 85, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 165, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/command.py", line 169, in call
    result = self._call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 285, in _call
    sym = sdb.get_symbol(frame_pc)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/target.py", line 85, in get_symbol
    return prog.symbol(sym)
OverflowError: int too big to convert
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

The issue wouldn't always be there which I found very weird.
Doing some printf-debugging though I found a pointer that
seemed to cause the issue consistently in the drgn REPL:
```
>>> prog.symbol(0xffffffff862423c0)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
OverflowError: int too big to convert
```

Looking at the code and the recent commits the error seemed
to stem from here:
```
~/drgn$ git diff
diff --git a/libdrgn/python/util.c b/libdrgn/python/util.c
index d0dfb2c..6c7ff2b 100644
--- a/libdrgn/python/util.c
+++ b/libdrgn/python/util.c
@@ -92,9 +92,11 @@ int index_converter(PyObject *o, void *p)
        index_obj = PyNumber_Index(o);
        if (!index_obj)
                return 0;
+
        if (arg->is_signed) {
                arg->svalue = PyLong_AsLongLong(index_obj);
                Py_DECREF(index_obj);
+               printf("serapheim test -> signed exit!\n");
                return (arg->svalue != -1LL || !PyErr_Occurred());
        } else {
                arg->uvalue = PyLong_AsUnsignedLongLong(index_obj);
```
```
>>> prog.symbol(0xffffffff862423c0)
serapheim test -> signed exit!
Traceback (most recent call last):
  File "<console>", line 1, in <module>
OverflowError: int too big to convert
```

The above was probably caused by this commit:
```
commit 2561226918555ad0d2d12ea6d3ed4cc9026c91d7
Author: Omar Sandoval <osandov@osandov.com>
Date:   Fri Nov 29 20:40:40 2019 -0800

    libdrgn: python: add signed integer support to index_converter

    This is preparation for the next change.
```

Applying the following change deals with the issue:
```
~/drgn$ git diff
diff --git a/libdrgn/python/program.c b/libdrgn/python/program.c
index fec3d2f..caea315 100644
--- a/libdrgn/python/program.c
+++ b/libdrgn/python/program.c
@@ -722,7 +722,7 @@ static PyObject *Program_symbol(Program *self, PyObject *args, PyObject *kwds)
 {
        static char *keywords[] = {"address", NULL};
        struct drgn_error *err;
-       struct index_arg address;
+       struct index_arg address = {};
        struct drgn_symbol *sym;
        PyObject *ret;
```
```
>>> prog.symbol(0xffffffff862423c0)
Symbol(name='__schedule', address=0xffffffff86242100, size=0x870)
```

The reason is that since `address` is not expicitly initialized
it gets a garbage value from the previous stack frame.

**Comment by osandov** [comment]
Oof, thanks for the thorough report. Looks like I messed this up in a few other places, too. I should try running the tests with valgrind.
