### ISSUE TITLE
Awkward error messages in certain inputs of prog.type()

### ISSUE THREAD

**Issue by sdimitro** [osandov/drgn#52]
This isn't a huge deal but I figured I'd report it for future reference.
```
>>> prog.type('struct')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line None
SyntaxError: expected identifier after '(null)'
```

The input to the command may be stupid but I think the error message is wrong. Did we meant to say `expected identifier after 'struct'`?

Furthermore, if we give an identifier of a struct type that doesn't exist we get the standard LookupError:
```
>>> prog.type('struct bogus')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
LookupError: could not find 'struct bogus'
```
But if we provide another keyword after this the syntax error gets confusing again:
```
>>> prog.type('struct int')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line None
SyntaxError: expected identifier after 'int'

>>> prog.type('struct int bogus')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line None
SyntaxError: expected identifier after 'int'
```

Again not a big deal as the above are extreme edge cases.

**Comment by osandov** [comment]
Oops, the parser is indeed looking at the wrong token when printing the error. Easy fix.
