### ISSUE TITLE
radix_tree_for_each doesn't work with flag XA_FLAGS_ALLOC1

### ISSUE THREAD

**Issue by mishuang2017** [osandov/drgn#61]
We have the following data structure:

struct mlx5_tc_ct_priv {
...
        struct idr fte_ids;
        struct xarray tuple_ids;
...
};

I can print fte_ids without problem. But I can't print tuple_ids. The error message is:

Traceback (most recent call last):
  File "/usr/local/bin/drgn", line 11, in <module>
    load_entry_point('drgn==0.0.4', 'console_scripts', 'drgn')()
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.4-py3.7-linux-x86_64.egg/drgn/internal/cli.py", line 129, in main
    runpy.run_path(args.script[0], init_globals=init_globals, run_name="__main__")
  File "/usr/lib64/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./test.py", line 53, in <module>
    for node in radix_tree_for_each(tuple_ids.address_of_()):
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.4-py3.7-linux-x86_64.egg/drgn/helpers/linux/radixtree.py", line 73, in radix_tree_for_each
    yield from aux(node, 0)
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.4-py3.7-linux-x86_64.egg/drgn/helpers/linux/radixtree.py", line 68, in aux
    index + (i << parent.shift.value_()),
  File "/usr/local/lib64/python3.7/site-packages/drgn-0.0.4-py3.7-linux-x86_64.egg/drgn/helpers/linux/radixtree.py", line 67, in aux
    cast(parent.type_, slot).read_(),
_drgn.FaultError: address is not mapped: 0x42c

When initializing the xarray with flag XA_FLAGS_ALLOC instead of XA_FLAGS_ALLOC1, it works:

(1, Object(prog, 'void *', value=0xffff9c884caf9628))
(2, Object(prog, 'void *', value=0xffff9c884caf9710))
(3, Object(prog, 'void *', value=0xffff9c884caf8228))
(4, Object(prog, 'void *', value=0xffff9c884caf8310))

**Comment by mishuang2017** [comment]
Thanks a lot for making this change. But sadly, I can't verify it because it seems we are not using that xarray anymore.
